### PR TITLE
Add documentation for BeginParams

### PR DESCRIPTION
**Pull request by samueldurantes**
### WHY are these changes introduced?

This PR aims to document the [`BeginParams`](https://github.com/Shopify/shopify-app-js/blob/557d76b42e47784eca365b3c5e595d1328d8e0f5/packages/apps/shopify-api/lib/auth/oauth/types.ts#L12) to make it easier to understand for newcomers who are integrating authentication using `@shopify/shopify-api` lib.

### WHAT is this pull request doing?

Adding documentation comments to the [`BeginParams`](https://github.com/Shopify/shopify-app-js/blob/557d76b42e47784eca365b3c5e595d1328d8e0f5/packages/apps/shopify-api/lib/auth/oauth/types.ts#L12) type.

## Type of change

- [ ] Patch: Bug (non-breaking change which fixes an issue)
- [x] Minor: New feature (non-breaking change which adds functionality)
- [ ] Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have used `yarn changeset` to create a draft changelog entry (do NOT update the `CHANGELOG.md` files manually)
- [ ] I have added/updated tests for this change
- [ ] I have documented new APIs/updated the documentation for modified APIs (for public APIs)

### CODE REVIEW

**Comment by lizkenyon** [comment]
Please sign the CLA and then I can merge this! 😊

**Comment by samueldurantes** [comment]
I have signed the CLA!

**Comment by samueldurantes** [comment]
> Please sign the CLA and then I can merge this! 😊

How can I do this?

**Comment by samueldurantes** [comment]
I have signed the CLA!

**Pull request merged**
