### PR TITLE
[Docs] Add DynamoDB table schema

### LINKED ISSUE #386: DynamoDB Session Storage Handler - Resource Not Found or Key unsupported by Schema
# Issue summary
Upon installing and adding the AWS DynamoDB Session Storage handler to the object with the following config:

```
sessionStorage: new DynamoDBSessionStorage({
    config: {
      region: "eu-west-2",
      credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID || "",
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || "",
      },
    },
  })
```

and the correct AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY values in my `.env` file, I am receiving a `Resource not Found` error when I follow the install link on a local preview and hit 'Install'. Logs below.

When I add the table in automatically, I receive a `Key provided does not match the schema` error in place of the previous error.

- `@shopify/shopify-app-*` package and version: `"@shopify/shopify-app-session-storage-dynamodb": "^1.0.4"`
- Node version: `v16.19.1`
- Operating system: `MacOS Ventura v13.4.1 (c)`

```
ResourceNotFoundException: Requested resource not found
    at de_ResourceNotFoundExceptionRes (/<My Project Folder>/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2878:23)
    at de_GetItemCommandError (/<My Project Folder>/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:1551:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /<My Project Folder>/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at /<My Project Folder>/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at /<My Project Folder>/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at /<My Project Folder>/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at DynamoDBSessionStorage.loadSession (/<My Project Folder>/node_modules/@shopify/shopify-app-session-storage-dynamodb/build/cjs/dynamodb.js:34:20)
    at AuthStrategy.ensureInstalledOnShop (/<My Project Folder>/node_modules/@shopify/shopify-app-remix/build/cjs/auth/admin/authenticate.js:256:28)
    at AuthStrategy.authenticateAndGetSessionContext (/<My Project Folder>/node_modules/@shopify/shopify-app-remix/build/cjs/auth/admin/authenticate.js:117:7)
```

## Expected behavior

I believe a table should be created under the name that I provide and the session data is automatically added to it, under the correct key.

## Actual behavior

The above errors are shown in both specified problems.

## Steps to reproduce the problem

1. Create a new Remix app from the Shopify Remix template.
2. Install the AWS DynamoDB Session Storage package.
3. Use the above config to add the DynamoDB Session Storage handler to the `shopifyApp` config.
4. Make sure to fill in a valid AWS Access Key ID and Secret Key into the environment variable provider.

Happy to amend this issue if not in correct format.

### PR DESCRIPTION
**Pull request by joelvh**
### WHY are these changes introduced?

Fixes #386 

It's unclear what the DynamoDB table schema should be.

### WHAT is this pull request doing?

This updates the docs with an example schema. (This is based on the [test suite](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-session-storage-dynamodb/src/__tests__/dynamodb.test.ts).)

## Type of change

- [x] Patch: Bug (non-breaking change which fixes an issue)
- [ ] Minor: New feature (non-breaking change which adds functionality)
- [ ] Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have used `yarn changeset` to create a draft changelog entry (do NOT update the `CHANGELOG.md` files manually)
- [ ] I have added/updated tests for this change
- [x] I have documented new APIs/updated the documentation for modified APIs (for public APIs)

### CODE REVIEW

**Comment by joelvh** [comment]
I have signed the CLA!

**Comment by lizkenyon** [comment]
@joelvh Could you add an empty changelog `yarn changeset --empty` as well run prettier on the markdown file to get the pipline to pass! :)

**Comment by joelvh** [comment]
@lizkenyon no problem - added!

**Comment by lizkenyon** [comment]
Hi @joelvh 

The pipeline is failing because of formatting. Running `yarn prettier --write packages/shopify-app-session-storage-dynamodb/README.md` should resolve this.

**Pull request merged**
